### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getCursors' of undefined

### ISSUE THREAD

**Issue by teosz** [extrabacon/atom-turbo-javascript#9]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.175.0
**System**: linux 3.13.0-48-generic
**Thrown From**: [turbo-javascript](https://github.com/extrabacon/atom-turbo-javascript) package, v0.0.7

### Stack Trace

Uncaught TypeError: Cannot read property 'getCursors' of undefined

```
At /home/teodor/.atom/packages/turbo-javascript/lib/turbo-javascript.coffee:8

TypeError: Cannot read property 'getCursors' of undefined
  at Object.module.exports.endLine (/home/teodor/.atom/packages/turbo-javascript/lib/turbo-javascript.coffee:8:11)
  at atom-workspace.<anonymous> (/home/teodor/.atom/packages/turbo-javascript/lib/turbo-javascript.coffee:3:65)
  at atom-workspace.handler (/usr/share/atom/resources/app/src/space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (/usr/share/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/usr/share/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:243:29)
  at /usr/share/atom/resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app/src/window-event-handler.js:170:20)

```

### Commands

```
     -0:00.0 turbo-javascript:end-line (atom-pane.pane.active)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "greti-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-grails, v0.1.0
autocomplete-css, v0.4.0
autocomplete-glsl, v0.1.4
autocomplete-haskell, v0.2.1
autocomplete-html, v0.3.0
autocomplete-paths, v1.0.2
greti-syntax, v0.3.1
ide-haskell, v0.3.0
language-csharp, v0.5.0
language-groovy-cloned-from-java, v0.2.0
language-javascript-jsx, v0.3.1
language-js-specs, v0.1.0
language-swift, v0.3.0
linter, v0.12.0
project-manager, v1.15.5
react, v0.9.10
recent-files, v0.3.0
refactor, v0.4.1

# Dev
No dev packages
```

/cc @atom/core

**Comment by extrabacon** [comment]
Obsolete? If not, feel free to reopen.
